#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://mariadb.ci3ovhrknnpp.ap-northeast-2.rds.amazonaws.com:3306/LaverMariaDB
#spring.datasource.username=root
#spring.datasource.password=Laver1234!
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none

server:
  port: 3333
#
spring:
  datasource:
#    maria:
    jdbc-url: jdbc:mariadb://mariadb.ci3ovhrknnpp.ap-northeast-2.rds.amazonaws.com:3306/LaverMariaDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Laver1234!
  jpa:
    properties:
      hibernate:
        format_sql: true
        temp:
        use_jdbc_metadata_defaults: false
    generate-ddl: true